### ISSUE TITLE
read excel exception

### ISSUE THREAD

**Issue by neal1991** [neal1991/lucene-test#12]
```
org.apache.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException: The supplied
data appears to be in the OLE2 Format. You are calling the part of POI that deal
s with OOXML (Office Open XML) Documents. You need to call a different part of P
OI to process this data (eg HSSF instead of XSSF)
        at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHe
lper.java:184)
        at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelp
er.java:241)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
        at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:2
91)
        at com.company.file.FileUtil.readExcel(FileUtil.java:107)
        at com.company.file.FileUtil.getFileBean(FileUtil.java:78)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:53)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:63)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:46)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:63)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:46)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:63)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:46)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:63)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:46)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:63)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:46)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:63)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:46)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:63)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:46)
        at com.company.test.TestIndex.executeIndex(TestIndex.java:34)
        at com.company.Main.main(Main.java:20)
```

**Comment by neal1991** [comment]
[1E39B01A.xlsx](https://github.com/neal1991/lucene-test/files/1273420/1E39B01A.xlsx)

**Comment by neal1991** [comment]
没有查到原因

**Comment by neal1991** [comment]
这个exception和文件类型有关系 这种文件不管用什么去读 都是有问题的
