### ISSUE TITLE
read7Z exception for pdf

### ISSUE THREAD

**Issue by neal1991** [neal1991/lucene-test#33]
```
2855 [main] ERROR com.company.file.FileUtil - IOException for file:test12/123123/新建文件夹 (3)/test-1.pdf
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:147)
	at org.apache.commons.compress.archivers.sevenz.BoundedSeekableByteChannelInputStream.read(BoundedSeekableByteChannelInputStream.java:83)
	at org.apache.commons.compress.archivers.sevenz.BoundedSeekableByteChannelInputStream.read(BoundedSeekableByteChannelInputStream.java:68)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at org.tukaani.xz.LZMA2InputStream.decodeChunkHeader(Unknown Source)
	at org.tukaani.xz.LZMA2InputStream.read(Unknown Source)
	at org.apache.commons.compress.utils.BoundedInputStream.read(BoundedInputStream.java:61)
	at org.apache.commons.compress.utils.ChecksumVerifyingInputStream.read(ChecksumVerifyingInputStream.java:85)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.read(SevenZFile.java:1000)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.read(SevenZFile.java:986)
	at com.company.file.FileUtil$1.read(FileUtil.java:299)
	at org.apache.pdfbox.io.ScratchFile.createBuffer(ScratchFile.java:421)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1141)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1040)
	at com.company.file.FileUtil.readPdf(FileUtil.java:359)
	at com.company.file.FileUtil.getContent(FileUtil.java:130)
	at com.company.file.FileUtil.getSevenFileBean(FileUtil.java:230)
	at com.company.file.FileUtil.read7Z(FileUtil.java:282)
	at com.company.file.FileUtil.getFolderFiles(FileUtil.java:66)
	at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:78)
	at com.company.file.FileUtil.getFolderFiles(FileUtil.java:54)
	at com.company.test.TestIndex.executeIndex(TestIndex.java:37)
	at com.company.Main.main(Main.java:22)
```

**Comment by neal1991** [comment]
docx is same
