### ISSUE TITLE
pdf大文件 java内存爆栈

### ISSUE THREAD

**Issue by neal1991** [neal1991/lucene-test#36]
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at org.apache.pdfbox.io.ScratchFileBuffer.addPage(ScratchFileBuffer.java
:132)
        at org.apache.pdfbox.io.ScratchFileBuffer.ensureAvailableBytesInPage(Scr
atchFileBuffer.java:184)
        at org.apache.pdfbox.io.ScratchFileBuffer.write(ScratchFileBuffer.java:2
36)
        at org.apache.pdfbox.io.RandomAccessOutputStream.write(RandomAccessOutpu
tStream.java:46)
        at org.apache.pdfbox.cos.COSStream$2.write(COSStream.java:271)
        at org.apache.pdfbox.pdfparser.COSParser.readValidStream(COSParser.java:
1142)
        at org.apache.pdfbox.pdfparser.COSParser.parseCOSStream(COSParser.java:9
70)
        at org.apache.pdfbox.pdfparser.COSParser.parseFileObject(COSParser.java:
781)
        at org.apache.pdfbox.pdfparser.COSParser.parseObjectDynamically(COSParse
r.java:742)
        at org.apache.pdfbox.pdfparser.COSParser.parseObjectDynamically(COSParse
r.java:673)
        at org.apache.pdfbox.pdfparser.COSParser.parseDictObjects(COSParser.java
:633)
        at org.apache.pdfbox.pdfparser.PDFParser.initialParse(PDFParser.java:241
)
        at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:276)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1143)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1040)
        at com.company.file.FileUtil.readPdf(FileUtil.java:349)
        at com.company.file.FileUtil.getContent(FileUtil.java:138)
        at com.company.file.FileUtil.getFileBean(FileUtil.java:112)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:69)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:89)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:62)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:89)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:62)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:89)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:62)
        at com.company.file.FileUtil.fileBeansAddForDirectory(FileUtil.java:89)
        at com.company.file.FileUtil.getFolderFiles(FileUtil.java:62)
        at com.company.test.TestIndex.executeIndex(TestIndex.java:34)
   at com.company.Main.main(Main.java:25)
```

**Comment by neal1991** [comment]
增加文件大小限制
